version: '3.4'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.35
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "4317-4318:4317-4318"
      - "16685-16686:16685-16686"

