receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  logging:
  file:
    path: ./export.json
  prometheus:
    endpoint: "0.0.0.0:9464"

processors:
  batch:

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging, file, prometheus]
      processors: [batch]